# Generated by Django 5.0.6 on 2024-06-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_topic_rename_create_room_created_room_host_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='create',
            new_name='created',
        ),
    ]
